## Data Loading
pd.read_csv(): Read a CSV file into a DataFrame.  
pd.read_excel(): Read an Excel file into a DataFrame.  
pd.read_sql(): Read SQL query or database table into a DataFrame.  
pd.read_json(): Read a JSON file into a DataFrame.  
pd.read_html(): Read HTML tables into a list of DataFrame objects.  
pd.read_clipboard(): Read text from the clipboard into a DataFrame.

In [2]:
import pandas as pd

In [4]:
df=pd.read_csv('E:\\Bytewise\\Datasets\\NFL Play by Play 2009-2016 (v3).csv')

C:\Users\H.H\AppData\Local\Temp\ipykernel_9200\1326689896.py:1: DtypeWarning: Columns (25,51) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv('E:\\Bytewise\\Datasets\\NFL Play by Play 2009-2016 (v3).csv')

In [5]:
df.head()

,Date,GameID,Drive,qtr,down,time,TimeUnder,TimeSecs,PlayTimeDiff,SideofField,...,yacEPA,Home_WP_pre,Away_WP_pre,Home_WP_post,Away_WP_post,Win_Prob,WPA,airWPA,yacWPA,Season
0,2009-09-10,2009091000,1,1,NaN,15:00,15,3600.0,0.0,TEN,...,NaN,0.485675,0.514325,0.546433,0.453567,0.485675,0.060758,NaN,NaN,2009
1,2009-09-10,2009091000,1,1,1.0,14:53,15,3593.0,7.0,PIT,...,1.146076,0.546433,0.453567,0.551088,0.448912,0.546433,0.004655,-0.032244,0.036899,2009
2,2009-09-10,2009091000,1,1,2.0,14:16,15,3556.0,37.0,PIT,...,NaN,0.551088,0.448912,0.510793,0.489207,0.551088,-0.040295,NaN,NaN,2009
3,2009-09-10,2009091000,1,1,3.0,13:35,14,3515.0,41.0,PIT,...,-5.031425,0.510793,0.489207,0.461217,0.538783,0.510793,-0.049576,0.106663,-0.156239,2009
4,2009-09-10,2009091000,1,1,4.0,13:27,14,3507.0,8.0,PIT,...,NaN,0.461217,0.538783,0.558929,0.441071,0.461217,0.097712,NaN,NaN,2009